apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: fiap-todo-api
  namespace: flux-system
spec:
  image: 777870534201.dkr.ecr.us-east-1.amazonaws.com/fiap-todo-api
  interval: 1m
  secretRef:
    name: ecr-credentials
